/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsIndexRouteImport } from './routes/boards/index'
import { Route as EditBoardBoardIdRouteImport } from './routes/edit-board.$boardId'
import { Route as BoardsBoardIdRouteImport } from './routes/boards/$boardId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditBoardBoardIdRoute = EditBoardBoardIdRouteImport.update({
  id: '/edit-board/$boardId',
  path: '/edit-board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/edit-board/$boardId': typeof EditBoardBoardIdRoute
  '/boards': typeof BoardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/edit-board/$boardId': typeof EditBoardBoardIdRoute
  '/boards': typeof BoardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/edit-board/$boardId': typeof EditBoardBoardIdRoute
  '/boards/': typeof BoardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/boards/$boardId'
    | '/edit-board/$boardId'
    | '/boards'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/boards/$boardId' | '/edit-board/$boardId' | '/boards'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/boards/$boardId'
    | '/edit-board/$boardId'
    | '/boards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  EditBoardBoardIdRoute: typeof EditBoardBoardIdRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-board/$boardId': {
      id: '/edit-board/$boardId'
      path: '/edit-board/$boardId'
      fullPath: '/edit-board/$boardId'
      preLoaderRoute: typeof EditBoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  EditBoardBoardIdRoute: EditBoardBoardIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
